language: java
before_install:
- chmod +x mvnw
branches:
  only:
  - master
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: restapis3v1
  api_key:
    secure: oj3HJQfhJBWd2zYT8QDDFnfoz0qH+Xmo6YcokELqnUNxL1UNG+owaR8EiLswjk0Q4IRBICl82xJPqvK0LdAP+wNHUvutcZ7+t614gonyY/CQe5zkGdGLva+S7gJx+FvGUoSU5ljSVZVEC6h77LOhywHJFHklJMqSlYiHswI6mArxlw/ljW5DdjUyieXE7AmUVvoWct7Y9EkGK4j3RlPZAeehjQXCLSzMfSC3wz7pteJTAenM9K0aDG6cTGmtQ9M3+Hx6XcQQJ+KMSKlNE8y1Q2pLFoWxlKfaWxS+lzdwlU+4dzV3fqhKnIEz11pPCdyyX2SptE2XDaLHXUSsimTK9zkKhNhColrYRUzj6UeilGPSBU6nREalk6WOcNY61/VjRUwqC7AMRnpBleEX+Z9KT1bi2zd3Xh75cRcvAEUTwMxhG3u5/KrYex13udZHMMCv1C3sa3GFUgFMXOB5MQBH4tEoW1kKrimi1hfsLirC1ngiGYQ1rsTzbA0XLfcWY43fb/9iWuEBe6c4FLcZaiD/ciU6a0tJ4k63MOPjT8kLiyYEkenbxuvOm3Yi6Av5FHsUtOd0z9oQHgkTxZH90TBFV+HYTPcpx4XmrtzSMXSWGo64d3K4tfQwWAbpLiVCZP8aobNDR4Skcr1w2BHerb9gKFtGS/QVsoXdi+E3lXpKdmk=
script: mvn clean verify
