language: java
sudo: false
before_install:
    - chmod +x mvnw

branches:
    only:
        - master

before_deploy:
    - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
    provider: heroku
    app: restapis3v1
    api_key:
        secure: "c3dcf06f-d475-4370-9a23-eba2197be309"

script: mvn clean verify