language: java
sudo: false
before_install:
- chmod +x mvnw
branches:
  only:
  - master
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: restapis3v1
  api_key:
    secure: S5vJaJKjbmH3fzg3sEv7v9r/dRclO7wvnS28ZZa+3Gyx6WBYnAawhWDY+X/6hvR7mi1Vwi0U3KYtt/fR+ru9aZoHAxiumqQEgDRbzJkAWXfxAN0sQn0flxOOV3hCLUNZ8ijN8wpm6qgtSxTuVBOorYfF1mAafAhoch3xyZmHZSs67wNdxVsQdGgxfP7fBwWfeLqCxPM8ZHMXAA/xqSVFkfKkoxM08KN7uK7mV792t4CJ5/8mTCYvi36cdNGT4lx2IP5p/xoN+s9ZM5MWFyfn/GyjaOxDBXS6JIFOhOYwUmYNxgcyTosIVSbEIaUfsg4HO2rCHfKNGMiMPs30t5BwGgBuY98P5YiXOCweYO1Ro6xlCf0sf7ly2QsXoN+/61SkqGA/MPTNWpl9G0Y27BzhN8KKYh6JxhXMan02/kU1OeLGOLu9YOzvMag1XLYCGgazMfvpGXMNADBE/E68dDU/UhkJTRmjlKPgPYmmLz2/sJIitRX4jvntSQFw9N06sa4KLWTtuTSKksOobpzbBWBAa+JrBMDC44yKWjs/V/piM/XxhFo4gXkT9y9AgaRM0BEDLnvWhUOUiDU+hOBAtadgzG6kJvq/bMSUQKoCxF2fFF+r589IdKQQQN4RM8hbAjtG7xyCKbKvIhCRS70+3bajKZoE51MEgWMckh3Y41YXP2g=
script: mvn clean verify
